name: Build FakeCamera APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: android-actions/setup-sdk@v2
      with:
        api-level: 33
        build-tools: '33.0.2'
    - name: Build APK
      run: |
        chmod +x gradlew
        ./gradlew clean :app:assembleDebug
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: fakecamera-apk
        path: app/build/outputs/apk/debug/app-debug.apk
